# =============================================================================
# Access Route4Me's logistics-as-a-service API using our Node.js SDK
#
# Copyright (C) 2016-2017 Route4Me
#
# =============================================================================

sudo: false

language: node_js

node_js:
  - 4
  - 6
  # - iojs # version 3.3, unsupported...
  - 7

env:
  global:
    - TEST_INTEGRATION=1

matrix:
  allow_failures:
    - node_js: 7  # unstable upstream
    - node_js: 8  # not on travis

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install -g npm
  - npm install -g gulp
  - npm install -g codecov
  - npm install -g bithound
  - npm install

script:
  - gulp build
  - gulp lint
  - gulp test
  - npm run coverage
  - codecov
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

deploy:
  provider: npm
  api_key:
    secure: "FT5Qlcnxz0Gg4i9HIj6vtjdMqYcuyhHs8B4sU6Df0bavMvpVucUNDkMXlcN/H3mPD1xE1/1tYhxZu2YF0n9m9yI89wqGQiywRdBAqT3hyKLrQOsFYkWkF322yviDQaZON2R6eEh43/e/iQH0ejxKDBYG4SF+cLEgR3EBcxBNsTI="
  email: npm@route4me.com
  on:
    tags: true                            # published only for tags
    node_js: 6                            # published only for one NPM version
    repo: route4me/route4me-nodejs-sdk    # published only from ONE repo
